# Generated by Django 5.2.5 on 2025-08-13 22:11

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=6)),
                ('daily_emails', models.PositiveIntegerField(default=2)),
                ('weekly_emails', models.PositiveIntegerField(default=5)),
                ('weekly_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, help_text='List of weekdays (0=Mon … 6=Sun) on which to send emails', size=7)),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('total_months', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_agent_id', models.CharField(blank=True, max_length=255)),
                ('recipient_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='E‑mail addresses that will receive the campaign’s messages', size=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
    ]
