# Generated by Django 5.2.5 on 2025-08-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='weekly_emails',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
